# Generated by Django 2.1.2 on 2019-02-13 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='prjData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('insert_date', models.DateTimeField(auto_now_add=True, verbose_name='Insert Date')),
            ],
        ),
        migrations.CreateModel(
            name='prjDataLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
                ('project_disc', models.CharField(default='', max_length=200)),
                ('api_key', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Creat Date')),
                ('project_creator', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='prjdatalabel',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speakapi.Project'),
        ),
        migrations.AddField(
            model_name='prjdata',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speakapi.prjDataLabel'),
        ),
        migrations.AddField(
            model_name='prjdata',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speakapi.Project'),
        ),
    ]
