# Generated by Django 2.1.2 on 2019-02-13 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('speakapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chartTitle', models.CharField(max_length=50)),
                ('chartType', models.CharField(choices=[('0', 'Line graph'), ('9', 'Thermal camera')], default='0', max_length=2)),
                ('chartDisc', models.CharField(default='', max_length=200)),
                ('chartXaxis', models.CharField(default='', max_length=200)),
                ('chartYaxis', models.CharField(default='', max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speakapi.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Trace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traceName', models.CharField(max_length=200)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataviewer.Chart')),
                ('xAxis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xaxis', to='speakapi.prjDataLabel')),
                ('yAxis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yaxis', to='speakapi.prjDataLabel')),
            ],
        ),
    ]
