FROM nginx

#COPY ./uwsgi_params /etc/nginx

#COPY ./cert /etc/nginx/cert

#CMD ["chmod", "644", "/etc/nginx/cert/*"]

#COPY ./tdspeak.conf /etc/nginx/conf.d

#COPY ./index.html /usr/share/nginx/html

#COPY ./static /usr/share/nginx/html/static

#COPY ./.well-known /usr/share/nginx/html/.well-known
